<?php
require_once ('./config/main_variables.php');
require_once ("./functions/php/sessions.inc");
require_once ('./config/dbconnect.php');
require_once ("./functions/php/knihovna.php");


//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('10','Poskytování služeb pro zemědělství, zahradnictví, rybníkářství, lesnictví a myslivost') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('20','Činnost odborného lesního hospodáře') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('30','Vyhotovování lesních hospodářských plánů a osnov') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('40','Nakládání s reprodukčním materiálem lesních dřevin') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('50','Chov zvířat a jejich výcvik (s výjimkou živočišné výroby)') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('60','Úprava nerostů, dobývání rašeliny a bahna') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('70','Výroba potravinářských a škrobárenských výrobků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('80','Pěstitelské pálení') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('90','Výroba krmiv, krmných směsí, doplňkových látek a premixů') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('100','Výroba textilií, textilních výrobků, oděvů a oděvních doplňků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('110','Výroba a opravy obuvi, brašnářského a sedlářského zboží') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('120','Zpracování dřeva, výroba dřevěných, korkových, proutěných a slaměných výrobků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('130','Výroba vlákniny, papíru a lepenky a zboží z těchto materiálů') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('140','Vydavatelské činnosti, polygrafická výroba, knihařské a kopírovací práce') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('150','Výroba, rozmnožování, distribuce, prodej, pronájem zvukových a zvukově-obrazových záznamů a výroba nenahraných nosičů údajů a záznamů') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('160','Výroba koksu, surového dehtu a jiných pevných paliv') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('170','Výroba chemických látek, vláken a přípravků a kosmetických prostředků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('180','Výroba hnojiv') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('190','Výroba plastových a pryžových výrobků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('200','Výroba a zpracování skla') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('210','Výroba stavebních hmot, porcelánových, keramických a sádrových výrobků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('220','Výroba brusiv a ostatních minerálních nekovových výrobků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('230','Broušení technického a šperkového kamene') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('240','Výroba a hutní zpracování železa, drahých a neželezných kovů a jejich slitin') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('250','Výroba kovových konstrukcí a kovodělných výrobků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('260','Umělecko-řemeslné zpracování kovů') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('270','Povrchové úpravy a svařování kovů a dalších materiálů') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('280','Výroba měřicích, zkušebních, navigačních, optických a fotografických přístrojů a zařízení') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('290','Výroba elektronických součástek, elektrických zařízení a výroba a opravy elektrických strojů, přístrojů a elektronických zařízení pracujících na malém napětí') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('300','Výroba neelektrických zařízení pro domácnost') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('310','Výroba strojů a zařízení') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('320','Výroba motorových a přípojných vozidel a karoserií') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('330','Stavba a výroba plavidel') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('340','Výroba, vývoj, projektování, zkoušky, instalace, údržba, opravy, modifikace a konstrukční změny letadel, motorů letadel, vrtulí, letadlových částí a zařízení a leteckých pozemních zařízení') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('350','Výroba drážních hnacích vozidel a drážních vozidel na dráze tramvajové, trolejbusové a lanové a železničního parku') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('360','Výroba jízdních kol, vozíků pro invalidy a jiných nemotorových dopravních prostředků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('370','Výroba a opravy čalounických výrobků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('380','Výroba, opravy a údržba sportovních potřeb, her, hraček a dětských kočárků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('390','Výroba zdravotnických prostředků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('400','Výroba a opravy zdrojů ionizujícího záření') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('410','Výroba školních a kancelářských potřeb, kromě výrobků z papíru, výroba bižuterie, kartáčnického a konfekčního zboží, deštníků, upomínkových předmětů') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('420','Výroba dalších výrobků zpracovatelského průmyslu') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('430','Provozování vodovodů a kanalizací a úprava a rozvod vody') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('440','Nakládání s odpady (vyjma nebezpečných)') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('450','Přípravné a dokončovací stavební práce, specializované stavební činnosti') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('460','Sklenářské práce, rámování a paspartování') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('470','Zprostředkování obchodu a služeb') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('480','Velkoobchod a maloobchod') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('490','Zastavárenská činnost a maloobchod s použitým zbožím') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('500','Údržba motorových vozidel a jejich příslušenství') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('510','Potrubní a pozemní doprava (vyjma železniční a silniční motorové dopravy)') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('520','Skladování, balení zboží, manipulace s nákladem a technické činnosti v dopravě') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('530','Zasilatelství a zastupování v celním řízení') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('540','Provozování poštovních a zahraničních poštovních služeb') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('550','Ubytovací služby') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('560','Poskytování software, poradenství v oblasti informačních technologií, zpracování dat, hostingové a související činnosti a webové portály') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('570','Činnost informačních a zpravodajských kanceláří') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('580','Realitní činnost, správa a údržba nemovitostí') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('590','Pronájem a půjčování věcí movitých') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('600','Poradenská a konzultační činnost, zpracování odborných studií a posudků') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('610','Projektování pozemkových úprav') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('620','Příprava a vypracování technických návrhů, grafické a kresličské práce') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('630','Projektování elektrických zařízení') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('640','Výzkum a vývoj v oblasti přírodních a technických věd nebo společenských věd') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('650','Testování, měření, analýzy a kontroly') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('660','Reklamní činnost, marketing, mediální zastoupení') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('670','Návrhářská, designérská, aranžérská činnost a modeling') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('680','Fotografické služby') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('690','Překladatelská a tlumočnická činnost') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('700','Služby v oblasti administrativní správy a služby organizačně hospodářské povahy') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('710','Provozování cestovní agentury a průvodcovská činnost v oblasti cestovního ruchu') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('720','Mimoškolní výchova a vzdělávání, pořádání kurzů, školení, včetně lektorské činnosti') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('730','Provozování kulturních, kulturně-vzdělávacích a zábavních zařízení, pořádání kulturních produkcí, zábav, výstav, veletrhů, přehlídek, prodejních a obdobných akcí') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('740','Provozování tělovýchovných a sportovních zařízení a organizování sportovní činnosti') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('750','Praní pro domácnost, žehlení, opravy a údržba oděvů, bytového textilu a osobního zboží') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('760','Poskytování technických služeb') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('770','Opravy a údržba potřeb pro domácnost, předmětů kulturní povahy, výrobků jemné mechaniky, optických přístrojů a měřidel') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('780','Poskytování služeb osobního charakteru a pro osobní hygienu') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('790','Poskytování služeb pro rodinu a domácnost') ");
//mysql_query("insert into list_free_trade (position,lang_cs)VALUES('800','Výroba, obchod a služby jinde nezařazené') ");
//


?>